# WARNING: Do not deploy this tutorial configuration directly to a production environment
#
# The tutorial docker-compose files have not been written for production deployment and will not 
# scale. A proper architecture has been sacrificed to keep the narrative focused on the learning 
# goals, they are just used to deploy everything onto a single Docker machine. All FIWARE components 
# are running at full debug and extra ports have been exposed to allow for direct calls to services. 
# They also contain various obvious security flaws - passwords in plain text, no load balancing,
# no use of HTTPS and so on. 
# 
# This is all to avoid the need of multiple machines, generating certificates, encrypting secrets
# and so on, purely so that a single docker-compose file can be read as an example to build on, 
# not use directly. 
# 
# When deploying to a production environment, please looking at the SmartSDK Recipes
# in order to scale up to a proper architecture:
# 
# see: https://smartsdk.github.io/smartsdk-recipes/
#
version: "3.5"
services:
  # Context broker (v2)
  orion-v2:
    image: fiware/orion:2.2.0
    hostname: orion-v2
    container_name: kipark-orion-v2
    depends_on:
      - mongo-db-v2
    networks:
      - main-network
    ports:
      - "1026:1026"
    command: -dbhost mongo-db-v2 -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion-v2:1026/version || exit 1

  # Context broker (LD)
  orion-ld:
    image: fiware/orion-ld
    hostname: orion-ld
    container_name: kipark-orion-ld
    depends_on:
      - mongo-db-ld
    networks:
      - main-network
    ports:
      - "1027:1026"
    command: -dbhost mongo-db-ld -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion-ld:1026/version || exit 1

  # Database (v2)
  mongo-db-v2:
    image: mongo:3.6
    hostname: mongo-db-v2
    container_name: kipark-db-mongo-v2
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - main-network
    command: --nojournal
    volumes:
      - mongo-db-v2:/data

  # Database (LD)
  mongo-db-ld:
    image: mongo:3.6
    hostname: mongo-db-ld
    container_name: kipark-db-mongo-ld
    expose:
      - "27018"
    ports:
      - "27018:27017"
    networks:
      - main-network
    command: --nojournal
    volumes:
      - mongo-db-ld:/data

  # Quantum Leap is persisting Short Term History to Crate-DB
  quantumleap:
    image: smartsdk/quantumleap:0.7.5
    hostname: quantumleap
    container_name: kipark-quantumleap
    networks:
      - main-network
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - CRATE_HOST=crate-db
    healthcheck:
      test: curl --fail -s http://quantumleap:8668/v2/version || exit 1

  # Crate-DB for holding time-series / history data
  crate-db:
    image: crate:3.3.5
    hostname: crate-db
    container_name: kipark-db-crate
    networks:
      - main-network
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    command: crate -Clicense.enterprise=false -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    volumes:
      - crate-db:/data

  # Kiel Parksensors Node.Js App
  kiel-parksensors:
    image: kiel-parksensors-node
    hostname: kiel-parksensors
    container_name: kipark-kiel-parksensors-node
    build: ./app
    env_file:
      - config.env
    networks:
      - main-network
    volumes:
      - ./app:/home/nodejs/kiel-parksensors
      - kiel-parksensors_node_modules:/home/nodejs/kiel-parksensors/node_modules

networks:
  main-network:
    driver: bridge

volumes:
  mongo-db-v2: 
  mongo-db-ld:
  crate-db:
  kiel-parksensors_node_modules:
