version: "3.5"
services:
  # Kiel Parksensors Node.Js App
  kiel-parksensors:
    image: kiel-parksensors-node
    hostname: kiel-parksensors
    container_name: kipark-kiel-parksensors-node
    build: ./app
    env_file:
      - config.env
    networks:
      - main-network
    volumes:
      - ./app:/home/nodejs/kiel-parksensors
      - kiel-parksensors_node_modules:/home/nodejs/kiel-parksensors/node_modules

networks:
  main-network:
    driver: bridge

volumes:
  kiel-parksensors_node_modules:
